n bands: 6
augmentation: False
prop zeros: 0.5
len data: 50000

loss: "crossentropy"
lr: 0.0001
momentum: 0.9
module: "resnet18"
batch size: 8
batch size test: 8
max epochs: 1
train prop: 0.6
val prop: 0.2
test prop: 0.2
accumulate batch : 3

mlflow: True