n bands: 6
augmentation: True
prop zeros: 0.5
len data limit: 1000000

loss: "bce"
optim: "adam"
lr: 0.0001
momentum: 0.9
module: "resnet18"
batch size: 128
batch size test: 128
max epochs: 100

train prop: 0.6
val prop: 0.2
test prop: 0.2
accumulate batch : 3

samplesubmission: True
mlflow: True